<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0</TargetFrameworks>
		<Version>2.1.0</Version>
		<Authors>Frends</Authors>
		<Copyright>Frends</Copyright>
		<Company>Frends</Company>
		<Product>Frends</Product>
		<PackageTags>Frends</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Description>Kafka produce Task.</Description>
		<PackageProjectUrl>https://frends.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/FrendsPlatform/Frends.Kafka</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<None Include="FrendsTaskMetadata.json" Pack="true" PackagePath="/">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Confluent.Kafka" Version="2.4.0" />
	  <PackageReference Include="Confluent.SchemaRegistry" Version="2.4.0" />
	  <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="2.4.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="8.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
</Project>